<?xml version="1.0" encoding="UTF-8"?>



<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author+,press,page,description?,photo*,cd?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT cd EMPTY>    
]>
<books>
      <book>
    <title>aaa</title>
    <author>bbbb</author>
    <press>ccccc</press>
    <page>300</page>
    <cd/>
    </book>
    </books>
    

    

