<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE items [
<!ELEMENT itmes (book|dvd)*>
<!ELEMENT book (title,author+,press,page,description?,photo*,(cd|tape|usb)?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT cd EMPTY>
<!ELEMENT tape EMPTY>
<!ELEMENT usb EMPTY>
<!ELEMENT dvd (title,price)>
<!ELEMENT price (#PCDATA)>
        
]>
<items>
	<book>
		<title>aaa</title>
		<author>bbbb</author>
		<press>ccccc</press>
		<page>300</page>
		<cd />
	</book>
	<dvd>
		<title>aaaa</title>
		<price>20000</price>
	</dvd>

	<book>
		<title>aaa</title>
		<author>bbbb</author>
		<press>ccccc</press>
		<page>300</page>
		<tape />
	</book>

	<book>
		<title>aaa</title>
		<author>bbbb</author>
		<press>ccccc</press>
		<page>300</page>
		<tape />
	</book>

</items>