<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author+,press,page,description?,photo*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
]>
<books>
      <book>
    <title>aaa</title>
    <author>bbbb</author>
    <press>ccccc</press>
    <page>300</page>
    </book>
    
    <book>
    <title>aaa</title>
    <author>bbbb</author>
    <author>okok</author>
    <press>ccccc</press>
    <page>500</page>
    <description>okokok</description>
    </book>
    
      <book>
    <title>aaa</title>
    <author>bbbb</author>
    <author>okok</author>
    <press>ccccc</press>
    <page>500</page>
    <photo>a1.gif</photo>
    <photo>a2.gif</photo>
    </book>
    
    </books>
    

