=== sehyun94/bitcamp/xml/ex4/test02.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트의 속성 타입 - IDREF, IDREFS
<!ATTLIST 태그명 
    속성명 IDREF #REQUIRED  
    속성명 IDREFS #REQUIRED-->
    

<!ENTITY % string "CDATA #REQUIRED">
<!ENTITY % coreattrs
    "name %string;
    id ID #REQUIRED"
>
<!ELEMENT items (author*,press*,book*)>
<!ELEMENT book (#PCDATA)>


<!ATTLIST book
    title %string;
    author IDREFS #REQUIRED
    press IDREF #REQUIRED
>

<!ELEMENT author (#PCDATA)>
<!ATTLIST author
    %coreattrs;
>
<!ELEMENT press (#PCDATA)>
<!ATTLIST press
    %coreattrs;
>

=== sehyun94/bitcamp/xml/ex4/test02.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트의 속성 타입 - IDREF, IDREFS
<!ATTLIST 태그명 
    속성명 IDREF #REQUIRED  
    속성명 IDREFS #REQUIRED
    
>
 -->
<!DOCTYPE items SYSTEM "test02.dtd">

<items>
    <author id="a001" name="홍길동"/> 
    <author id="a002" name="임꺽정"/> 
    <author id="a003" name="유관순"/>
    
    <press id="p001" name="비트출판사"/> 
    <press id="p002" name="위키북스"/> 
    <press id="p003" name="프리렉"/>
    
    <book title="aaaa" author="a003" press="p001">
    </book>
      
</items>
